In [2]:
import numpy as np
import torch
import matplotlib.pyplot as plt

### Working with Tensors

In [3]:
x = torch.ones(3, 2)
x = torch.rand(3, 2)

In [4]:
print(x)

tensor([[0.7865, 0.7955],
        [0.4329, 0.2180],
        [0.1911, 0.3456]])


In [6]:
x = torch.linspace(0, 1, steps = 5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [9]:
x = torch.tensor(
    [[1, 3],
     [3, 4],
     [5, 6]]
)

In [10]:
print(x.size())
print(x[:, 1]) # Slicing

torch.Size([3, 2])
tensor([3, 4, 6])


In [11]:
y = x[1, 1]
print(y)
y.item()

tensor(4)


4

In [12]:
print(x)
y = x.view(2, 3) # Reshaping
y

tensor([[1, 3],
        [3, 4],
        [5, 6]])


tensor([[1, 3, 3],
        [4, 5, 6]])

In [13]:
x.view(6, -1)

tensor([[1],
        [3],
        [3],
        [4],
        [5],
        [6]])

In [14]:
print(torch.cuda.device_count())

0


### Autograd

In [15]:
x = torch.ones([3, 2], requires_grad= True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [16]:
y = x + 5

In [17]:
z = y * y + 1

In [18]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [19]:
t.backward()

In [22]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [24]:
x = torch.randn([20, 1], requires_grad = True)
y = 3 * x - 2

In [25]:
w = torch.tensor([1.], requires_grad= True)
b = torch.tensor([1.], requires_grad= True)

y_hat = w * x + b
loss = torch.sum((y_hat - y) ** 2)

In [26]:
print(loss)

tensor(229.1382, grad_fn=<SumBackward0>)


In [27]:
loss.backward()

In [28]:
print(w.grad, b.grad)

tensor([-50.8250]) tensor([118.8755])


### Autograd Example

In [29]:
learning_rate = 0.01
w = torch.tensor([1.], requires_grad= True)
b = torch.tensor([1.], requires_grad= True)

print(w.item(), b.item())

for i in range(10):
    x = torch.randn([20, 1])
    y = 3 * x - 2

    y_hat = w * x + b
    loss = torch.sum((y_hat - y) ** 2)

    loss.backward()

    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        w.grad.zero_()
        b.grad.zero_()

    print(w.item(), b.item())

1.0 1.0
1.510342001914978 0.07489341497421265
1.9854180812835693 -0.6482095122337341
2.3681883811950684 -1.2323269844055176
2.7859230041503906 -1.6519997119903564
2.847402811050415 -1.8001338243484497
2.873485803604126 -1.8582593202590942
2.9073643684387207 -1.9120476245880127
2.9572594165802 -1.9497689008712769
2.9872007369995117 -1.9764890670776367
2.992755889892578 -1.9858235120773315
